const adventurerName = "Euca";
const adventurerFriend = "Lyca";
const newFriend = "Joley";
const hikerFriend = "Kyle";
const location1 = "Home";
const location2 = "The Mysterious Mountain";
const beatenTrail = "the Beaten Trail";
let applesInBag = 5;
let friedChickenInBag = 9;
let cheese = 0;
let totalFood = applesInBag + friedChickenInBag + cheese;
console.log("Once upon a time, a mage named " + adventurerName + ", and her shapeshifter friend " + adventurerFriend + ", decided to leave " + location1 + " to go on an adventure.");
console.log("They took a bag of food with them.");
console.log("The bag held " + applesInBag + " apples, and " + friedChickenInBag + " pieces of fried chicken.");
console.log("The two snuck out of their " + location1 + " and to freedom!");
console.log("And so, the two set out on a grand journey, which, little did they know, would soon be filled with danger.");
let eSpells = 3;
const eSpell1 = "Fireball";
const eSpell2 = "Lightning";
const eSpell3 = "Gales";
const lShape1 = "Human";
const lShape2 = "Wolf";
let evilBugs = 3;
let shadowCreatures = 8;
let miniBoss = 1;
let trainingDummy = 2;
console.log("The two girls then went to their seceret training shack in the woods.");
console.log("They wanted to train before setting off to " + location2 + ".");
console.log("While " + adventurerFriend + " practiced her shifting, " + adventurerName + " went to practice her spells.");
console.log("'" + eSpell1 + "'" + "! She shouted, utterly destoying the training dummy.");
trainingDummy = trainingDummy - 1;
console.log("'Well, we've got " + trainingDummy + " training dummy left.' called "  + adventurerName + ".");
console.log("'Okay!' " + adventurerFriend + " shouted back.");
console.log("'I'll tear up that last one' said " + adventurerFriend + ", barreling by in " + lShape2 + " form.");
console.log(adventurerFriend + " then tore the training dummy to shreds.");
trainingDummy = trainingDummy - 1;
console.log("'Well, that was the last one.' said " + adventurerName + ", as " + adventurerFriend + " shifted back into " + lShape1 + " form.");
console.log("'We should get going now,' said " + adventurerName + ".");
console.log ("'Yeah, okay.' said " + adventurerFriend + ".");
console.log("And so, " + adventurerName + " and " + adventurerFriend + " set off on " + beatenTrail + ".");
console.log("The pair soon went by a forest. 'Uhhhh, " + adventurerName + "?' " + adventurerFriend + " said nervously.");
console.log("'What?' " + adventurerName + " replied.");
console.log("'WHAT ARE THOSE?!?!' screeched " + adventurerFriend + ".");
console.log("A trio of demon spiders craweled out of the trees. 'AAAAAAAAAAAAAAAAAAHH!' They srceamed.");
console.log(eSpell1 + "! ")